"""initial schema

Revision ID: 4afec5977568
Revises: 
Create Date: 2026-09-07 22:28:44.689623

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4afec5977568'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('section')
    )
    op.create_table('indexer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prowlarr_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('privacy', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_seeders', sa.Integer(), nullable=False),
    sa.Column('supports_music_search', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indexer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indexer_prowlarr_id'), ['prowlarr_id'], unique=True)

    op.create_table('library_album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('album_artist', sa.String(length=500), nullable=False),
    sa.Column('album_artist_id', sa.String(length=64), nullable=True),
    sa.Column('release_mbid', sa.String(length=64), nullable=True),
    sa.Column('release_group_mbid', sa.String(length=64), nullable=True),
    sa.Column('artist_mbid', sa.String(length=64), nullable=True),
    sa.Column('fuzzy_key', sa.String(length=600), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('is_lossless', sa.Boolean(), nullable=False),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('image_tag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_album', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_album_fuzzy_key'), ['fuzzy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_album_jellyfin_id'), ['jellyfin_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_library_album_release_group_mbid'), ['release_group_mbid'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_album_release_mbid'), ['release_mbid'], unique=False)

    op.create_table('library_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('mbid', sa.String(length=64), nullable=True),
    sa.Column('fuzzy_key', sa.String(length=600), nullable=False),
    sa.Column('album_count', sa.Integer(), nullable=False),
    sa.Column('image_tag', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library_artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_artist_fuzzy_key'), ['fuzzy_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_artist_jellyfin_id'), ['jellyfin_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_library_artist_mbid'), ['mbid'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jellyfin_user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('can_request', sa.Boolean(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=True),
    sa.Column('weekly_quota', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('primary_image_tag', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_jellyfin_user_id'), ['jellyfin_user_id'], unique=True)

    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('release_group_mbid', sa.String(length=64), nullable=False),
    sa.Column('release_mbid', sa.String(length=64), nullable=True),
    sa.Column('artist_mbid', sa.String(length=64), nullable=True),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('album_title', sa.String(length=500), nullable=False),
    sa.Column('primary_type', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_upgrade', sa.Boolean(), nullable=False),
    sa.Column('replaces_path', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retry_after', sa.DateTime(), nullable=True),
    sa.Column('provider_key', sa.String(length=64), nullable=True),
    sa.Column('provider_label', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('destination_path', sa.Text(), nullable=True),
    sa.Column('exhausted_providers', sa.JSON(), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_release_group_mbid'), ['release_group_mbid'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_status'), ['status'], unique=False)
        batch_op.create_index('ix_request_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_user_id'), ['user_id'], unique=False)

    op.create_table('watched_artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_mbid', sa.String(length=64), nullable=False),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('auto_download', sa.Boolean(), nullable=False),
    sa.Column('include_types', sa.JSON(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('seen_release_groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'artist_mbid', name='uq_watch_user_artist')
    )
    with op.batch_alter_table('watched_artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watched_artist_artist_mbid'), ['artist_mbid'], unique=False)
        batch_op.create_index(batch_op.f('ix_watched_artist_user_id'), ['user_id'], unique=False)

    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('release_group_mbid', sa.String(length=64), nullable=False),
    sa.Column('artist_name', sa.String(length=500), nullable=False),
    sa.Column('album_title', sa.String(length=500), nullable=False),
    sa.Column('artist_mbid', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'release_group_mbid', name='uq_wishlist_user_release_group')
    )
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_item_release_group_mbid'), ['release_group_mbid'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_item_user_id'), ['user_id'], unique=False)

    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('downloaded', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('eta', sa.Integer(), nullable=True),
    sa.Column('content_path', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_request_id'), ['request_id'], unique=False)

    op.create_table('download_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('provider_label', sa.String(length=255), nullable=False),
    sa.Column('candidate_title', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_attempt_request_id'), ['request_id'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_state'), ['state'], unique=False)
        batch_op.create_index('ix_job_state_run_after', ['state', 'run_after'], unique=False)

    op.create_table('request_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_event_request_id'), ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_event_request_id'))

    op.drop_table('request_event')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_state_run_after')
        batch_op.drop_index(batch_op.f('ix_job_state'))
        batch_op.drop_index(batch_op.f('ix_job_run_after'))
        batch_op.drop_index(batch_op.f('ix_job_request_id'))
        batch_op.drop_index(batch_op.f('ix_job_kind'))

    op.drop_table('job')
    with op.batch_alter_table('download_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_attempt_request_id'))

    op.drop_table('download_attempt')
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_request_id'))

    op.drop_table('download')
    with op.batch_alter_table('wishlist_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_item_release_group_mbid'))

    op.drop_table('wishlist_item')
    with op.batch_alter_table('watched_artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watched_artist_user_id'))
        batch_op.drop_index(batch_op.f('ix_watched_artist_artist_mbid'))

    op.drop_table('watched_artist')
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_user_id'))
        batch_op.drop_index('ix_request_status_created')
        batch_op.drop_index(batch_op.f('ix_request_status'))
        batch_op.drop_index(batch_op.f('ix_request_release_group_mbid'))
        batch_op.drop_index(batch_op.f('ix_request_created_at'))

    op.drop_table('request')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_jellyfin_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('library_artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_artist_mbid'))
        batch_op.drop_index(batch_op.f('ix_library_artist_jellyfin_id'))
        batch_op.drop_index(batch_op.f('ix_library_artist_fuzzy_key'))

    op.drop_table('library_artist')
    with op.batch_alter_table('library_album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_album_release_mbid'))
        batch_op.drop_index(batch_op.f('ix_library_album_release_group_mbid'))
        batch_op.drop_index(batch_op.f('ix_library_album_jellyfin_id'))
        batch_op.drop_index(batch_op.f('ix_library_album_fuzzy_key'))

    op.drop_table('library_album')
    with op.batch_alter_table('indexer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indexer_prowlarr_id'))

    op.drop_table('indexer')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
